// Package wg is a thin wrapper over `wg` + `ip` + `rosenpass` system commands,
// called from the API when we provision a new peer for a paying customer.
//
// Phase 0 is intentionally shell-out: it keeps us aligned with server/scripts/
// and avoids pulling in wgctrl + a netlink dance. If we outgrow it, this is
// the single file to replace.
package wg

import (
	"bytes"
	"fmt"
	"net"
	"os/exec"
	"strings"
)

type Config struct {
	Iface      string // wg0
	ServerPub  string // server's WireGuard public key (base64)
	Endpoint   string // fi1.cloakvpn.ai:51820
	DNS        string // 10.99.0.1
	AllowedIPs string // "0.0.0.0/0, ::/0"
	SubnetCIDR string // 10.99.0.0/24
}

type Controller struct{ cfg Config }

func NewController(c Config) *Controller { return &Controller{cfg: c} }

// ClientConfig is what we hand back to the app. The Rosenpass keys are
// generated by `rosenpass gen-keys` and paired with WireGuard identity.
type ClientConfig struct {
	InterfacePrivateKey string // base64
	InterfaceAddress    string // "10.99.0.5/32"
	InterfaceDNS        string
	PeerPublicKey       string // server's wg pub
	PeerEndpoint        string
	PeerAllowedIPs      string
	RosenpassPeerPub    string // base64 of server's rosenpass static pub
	RosenpassListen     string // "fi1.cloakvpn.ai:9999"
	RosenpassClientSK   string // client rosenpass secret
	RosenpassClientPK   string // client rosenpass public (registered on server)
	AssignedIP          string // "10.99.0.5"
}

// Provision is the end-to-end "add a new device" flow. It:
//  1. Picks the next free IP in SubnetCIDR (naive O(n) scan; fine for Phase 0).
//  2. Runs `wg genkey` / `wg pubkey` to mint a WireGuard keypair on the server.
//  3. Runs `rosenpass gen-keys` to mint a Rosenpass keypair.
//  4. Adds the peer to the running wg interface via `wg set`.
//  5. Registers the rosenpass public key with rosenpass.service (via its config reload).
//  6. Returns a ClientConfig the app encodes into its TunnelManager.
//
// usedIPs is the set of IPs already allocated (pulled from store.Devices).
func (c *Controller) Provision(usedIPs []string) (*ClientConfig, error) {
	ip, err := c.nextFreeIP(usedIPs)
	if err != nil {
		return nil, err
	}

	wgPriv, err := run("wg", "genkey")
	if err != nil {
		return nil, fmt.Errorf("wg genkey: %w", err)
	}
	wgPub, err := runStdin(wgPriv, "wg", "pubkey")
	if err != nil {
		return nil, fmt.Errorf("wg pubkey: %w", err)
	}

	// Phase 0 stub: rosenpass key generation is done once on the server; the
	// client's PSK is derived via the Rosenpass handshake, not a pre-shared
	// static key here. We only need the client's Rosenpass public key to be
	// registered as a peer in /etc/rosenpass/rosenpass.conf.
	// The real implementation will call `rosenpass gen-keys --public-key …`.
	rpClientPK := "REPLACE_WITH_ROSENPASS_CLIENT_PK"
	rpClientSK := "REPLACE_WITH_ROSENPASS_CLIENT_SK"

	// Add peer to the running wg interface. AllowedIPs for a client is just
	// its /32 on the server side.
	cmd := exec.Command("wg", "set", c.cfg.Iface,
		"peer", strings.TrimSpace(wgPub),
		"allowed-ips", ip+"/32")
	if out, err := cmd.CombinedOutput(); err != nil {
		return nil, fmt.Errorf("wg set: %w: %s", err, out)
	}
	// Persist to /etc/wireguard/wg0.conf so it survives a reboot.
	if out, err := exec.Command("wg-quick", "save", c.cfg.Iface).CombinedOutput(); err != nil {
		return nil, fmt.Errorf("wg-quick save: %w: %s", err, out)
	}

	return &ClientConfig{
		InterfacePrivateKey: strings.TrimSpace(wgPriv),
		InterfaceAddress:    ip + "/32",
		InterfaceDNS:        c.cfg.DNS,
		PeerPublicKey:       c.cfg.ServerPub,
		PeerEndpoint:        c.cfg.Endpoint,
		PeerAllowedIPs:      c.cfg.AllowedIPs,
		RosenpassListen:     strings.Split(c.cfg.Endpoint, ":")[0] + ":9999",
		RosenpassClientSK:   rpClientSK,
		RosenpassClientPK:   rpClientPK,
		AssignedIP:          ip,
	}, nil
}

// Revoke removes a peer from the running wg interface and persists.
func (c *Controller) Revoke(wgPubkey string) error {
	cmd := exec.Command("wg", "set", c.cfg.Iface, "peer", wgPubkey, "remove")
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("wg set remove: %w: %s", err, out)
	}
	if out, err := exec.Command("wg-quick", "save", c.cfg.Iface).CombinedOutput(); err != nil {
		return fmt.Errorf("wg-quick save: %w: %s", err, out)
	}
	return nil
}

func (c *Controller) nextFreeIP(used []string) (string, error) {
	_, ipnet, err := net.ParseCIDR(c.cfg.SubnetCIDR)
	if err != nil {
		return "", err
	}
	skip := map[string]struct{}{}
	for _, u := range used {
		skip[u] = struct{}{}
	}
	ip := ipnet.IP.To4()
	// Reserve .0 (network), .1 (server), .255 (broadcast).
	for i := 2; i < 255; i++ {
		candidate := net.IPv4(ip[0], ip[1], ip[2], byte(i)).String()
		if _, taken := skip[candidate]; taken {
			continue
		}
		return candidate, nil
	}
	return "", fmt.Errorf("subnet %s exhausted", c.cfg.SubnetCIDR)
}

func run(name string, args ...string) (string, error) {
	var buf bytes.Buffer
	cmd := exec.Command(name, args...)
	cmd.Stdout = &buf
	if err := cmd.Run(); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func runStdin(stdin, name string, args ...string) (string, error) {
	var buf bytes.Buffer
	cmd := exec.Command(name, args...)
	cmd.Stdin = strings.NewReader(stdin)
	cmd.Stdout = &buf
	if err := cmd.Run(); err != nil {
		return "", err
	}
	return buf.String(), nil
}
