#!/usr/bin/env bash
# build-xcframework.sh — produce RosenpassFFI.xcframework + RosenpassFFI.swift
#
# Output (all under ./out/):
#   RosenpassFFI.xcframework/   — drag into Xcode "Frameworks, Libraries, and
#                                  Embedded Content"
#   RosenpassFFI.swift          — Swift bindings file generated by
#                                  uniffi-bindgen, drag into the iOS app target
#   rosenpass_ffiFFI.modulemap  — module map (Xcode picks this up via the
#                                  xcframework's include/ dir)
#   rosenpass_ffiFFI.h          — C header
#
# Prerequisites (one-time setup; see README.md for full details):
#   brew install cmake rustup
#   rustup-init -y
#   rustup toolchain install 1.88.0
#   rustup target add aarch64-apple-ios aarch64-apple-ios-sim --toolchain 1.88.0
#   sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
#   sudo xcodebuild -license accept
#
# Usage:
#   ./build-xcframework.sh           # debug build (faster iteration)
#   ./build-xcframework.sh --release # release build (ship this)

set -euo pipefail

PROFILE="${1:---debug}"
case "$PROFILE" in
  --release) PROFILE_FLAG="--release"; PROFILE_DIR="release" ;;
  --debug|"") PROFILE_FLAG="";          PROFILE_DIR="debug" ;;
  *) echo "Unknown profile: $PROFILE (want --debug or --release)" >&2; exit 1 ;;
esac

TOOLCHAIN="1.88.0"
LIB_NAME="librosenpassffi.a"
CRATE_NAME="rosenpassffi"   # matches [lib].name in Cargo.toml

# Pin the iOS deployment target. Without this, rustc defaults to iOS 10
# (2016) but the Xcode 26 SDK assumes iOS 14+ for builtins like
# __chkstk_darwin, producing "symbol not found" link errors.
# iOS 14 (2020) covers >99% of active devices in 2026.
export IPHONEOS_DEPLOYMENT_TARGET="14.0"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

OUT_DIR="$SCRIPT_DIR/out"
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

color() { printf "\033[1;34m[xcfw]\033[0m %s\n" "$*"; }

# -----------------------------------------------------------------------------
# 1. Cross-compile for both targets.
# -----------------------------------------------------------------------------

color "building $PROFILE_DIR for aarch64-apple-ios (device)"
cargo "+$TOOLCHAIN" build $PROFILE_FLAG \
    --target aarch64-apple-ios \
    --no-default-features

color "building $PROFILE_DIR for aarch64-apple-ios-sim (Apple Silicon Simulator)"
SDK="$(xcrun --sdk iphonesimulator --show-sdk-path)"
BINDGEN_EXTRA_CLANG_ARGS_aarch64_apple_ios_sim="--target=arm64-apple-ios14.0-simulator --sysroot=$SDK" \
    cargo "+$TOOLCHAIN" build $PROFILE_FLAG \
        --target aarch64-apple-ios-sim \
        --no-default-features

DEVICE_LIB="target/aarch64-apple-ios/$PROFILE_DIR/$LIB_NAME"
SIM_LIB="target/aarch64-apple-ios-sim/$PROFILE_DIR/$LIB_NAME"

[[ -f "$DEVICE_LIB" ]] || { echo "device lib not found at $DEVICE_LIB" >&2; exit 1; }
[[ -f "$SIM_LIB"    ]] || { echo "sim lib not found at $SIM_LIB"       >&2; exit 1; }

color "device lib: $(du -h "$DEVICE_LIB" | cut -f1) at $DEVICE_LIB"
color "sim lib:    $(du -h "$SIM_LIB"    | cut -f1) at $SIM_LIB"

# -----------------------------------------------------------------------------
# 2. Generate Swift bindings via uniffi-bindgen.
#
# uniffi 0.27 ships a `uniffi-bindgen` binary that introspects a built
# library and emits Swift code. We invoke it via `cargo run --bin
# uniffi-bindgen` so we don't depend on a separate global install.
# -----------------------------------------------------------------------------

color "generating Swift bindings via uniffi-bindgen"
mkdir -p "$OUT_DIR/Generated"
cargo "+$TOOLCHAIN" run --features=uniffi-cli --bin uniffi-bindgen -- \
    generate \
    --library "$DEVICE_LIB" \
    --language swift \
    --out-dir "$OUT_DIR/Generated"

# uniffi emits three files we care about:
#   rosenpass_ffiFFI.h       — C header, lives inside the xcframework
#   rosenpass_ffiFFI.modulemap — module map, lives inside the xcframework
#   RosenpassFFI.swift       — Swift bindings, drag into Xcode app target
ls "$OUT_DIR/Generated/"

# -----------------------------------------------------------------------------
# 3. Build the xcframework.
#
# xcodebuild -create-xcframework wants paired (library, headers) tuples.
# We give it both architectures plus the same headers/modulemap dir.
# -----------------------------------------------------------------------------

color "assembling RosenpassFFI.xcframework"

# Move the C header + modulemap into a fresh include/ dir for both archs.
INCL_DIR="$OUT_DIR/include"
mkdir -p "$INCL_DIR"
mv "$OUT_DIR/Generated/${CRATE_NAME}FFI.h"          "$INCL_DIR/" 2>/dev/null || true
mv "$OUT_DIR/Generated/${CRATE_NAME}FFI.modulemap"  "$INCL_DIR/module.modulemap" 2>/dev/null || true

# Sanity: must have both headers and modulemap, otherwise Xcode can't import.
[[ -f "$INCL_DIR/module.modulemap" ]] || {
  echo "module.modulemap missing in $INCL_DIR — uniffi-bindgen output changed?" >&2
  ls "$OUT_DIR/Generated/" >&2
  exit 1
}

XCFW="$OUT_DIR/RosenpassFFI.xcframework"
xcodebuild -create-xcframework \
    -library "$DEVICE_LIB" -headers "$INCL_DIR" \
    -library "$SIM_LIB"    -headers "$INCL_DIR" \
    -output  "$XCFW" >/dev/null

color "✓ XCFramework built: $XCFW"
color "✓ Swift bindings:    $OUT_DIR/Generated/RosenpassFFI.swift"
echo
cat <<EOF

Next step — wire into Xcode:
  1. Drag $XCFW into the CloakVPN target in Xcode → "Frameworks,
     Libraries, and Embedded Content". Embed = "Do not embed" (it's a
     static library, not a dynamic framework).
  2. Drag $OUT_DIR/Generated/RosenpassFFI.swift into the CloakVPN
     target's source files.
  3. import RosenpassFFI
  4. let v = rosenpassVersion()  // smoke test — returns the rosenpass
                                 // git rev + KEM combo string.

EOF
