#!/usr/bin/env bash
# Cloak VPN — Server bootstrap script
# Target: Ubuntu 24.04 LTS, fresh install, run as root.
#
# Installs:
#   - WireGuard
#   - Rosenpass (post-quantum key-exchange daemon that feeds WireGuard PSKs)
#   - UFW firewall with a deny-by-default policy
#   - systemd units for both daemons
#   - RAM-only /var/log mount (tmpfs) for no-logs posture
#
# After running, the script prints:
#   - Server WireGuard public key
#   - Server Rosenpass public key
#   - A ready-to-paste client config block

set -euo pipefail

log()  { printf "\033[1;34m[cloak]\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m[warn]\033[0m %s\n" "$*"; }
die()  { printf "\033[1;31m[err]\033[0m %s\n" "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root (use sudo)."

# ---------- Configurable --------------------------------------------------
WG_IFACE="${WG_IFACE:-wg0}"
WG_PORT="${WG_PORT:-51820}"
RP_PORT="${RP_PORT:-9999}"
WG_NET_V4="${WG_NET_V4:-10.99.0.0/24}"
WG_NET_V6="${WG_NET_V6:-fd42:99::/64}"
SERVER_V4="${SERVER_V4:-10.99.0.1}"
SERVER_V6="${SERVER_V6:-fd42:99::1}"
CLIENT_V4="${CLIENT_V4:-10.99.0.2}"
CLIENT_V6="${CLIENT_V6:-fd42:99::2}"
ETH_IFACE="${ETH_IFACE:-$(ip -o -4 route show default | awk '{print $5; exit}')}"
PUBLIC_IP="${PUBLIC_IP:-$(curl -fsSL https://api.ipify.org || hostname -I | awk '{print $1}')}"

ETC_WG=/etc/wireguard
ETC_RP=/etc/rosenpass
# --------------------------------------------------------------------------

log "Public IP detected: $PUBLIC_IP (outbound iface: $ETH_IFACE)"
log "WireGuard iface $WG_IFACE on :$WG_PORT ; Rosenpass on :$RP_PORT"

# ---------- Update & base packages ----------------------------------------
log "apt update and install base packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
  curl ca-certificates gnupg ufw \
  wireguard wireguard-tools \
  qrencode jq iproute2 \
  build-essential pkg-config \
  rosenpass

# If rosenpass is not in apt (Ubuntu <24.10), install from cargo as fallback.
if ! command -v rosenpass >/dev/null 2>&1; then
  warn "rosenpass not in apt; installing via cargo"
  apt-get install -y -qq cargo
  cargo install --locked rosenpass
  cp "$HOME/.cargo/bin/rosenpass" /usr/local/bin/rosenpass
fi

# ---------- Kernel / sysctl ----------------------------------------------
log "Enabling IPv4/IPv6 forwarding"
cat >/etc/sysctl.d/99-cloak-vpn.conf <<EOF
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1
net.ipv4.conf.all.rp_filter=2
EOF
sysctl --system >/dev/null

# ---------- WireGuard keys ------------------------------------------------
install -m 700 -d "$ETC_WG"
if [[ ! -f $ETC_WG/server.key ]]; then
  log "Generating WireGuard server keypair"
  umask 077
  wg genkey | tee "$ETC_WG/server.key" | wg pubkey >"$ETC_WG/server.pub"
fi
WG_SERVER_PRIV=$(cat "$ETC_WG/server.key")
WG_SERVER_PUB=$(cat "$ETC_WG/server.pub")

if [[ ! -f $ETC_WG/client1.key ]]; then
  log "Generating WireGuard client1 keypair (test client)"
  wg genkey | tee "$ETC_WG/client1.key" | wg pubkey >"$ETC_WG/client1.pub"
fi
WG_CLIENT_PRIV=$(cat "$ETC_WG/client1.key")
WG_CLIENT_PUB=$(cat "$ETC_WG/client1.pub")

# ---------- Rosenpass keys ------------------------------------------------
install -m 700 -d "$ETC_RP"
if [[ ! -f $ETC_RP/server.rosenpass-secret ]]; then
  log "Generating Rosenpass server keypair"
  rosenpass gen-keys \
    --secret-key "$ETC_RP/server.rosenpass-secret" \
    --public-key "$ETC_RP/server.rosenpass-public"
fi
if [[ ! -f $ETC_RP/client1.rosenpass-secret ]]; then
  log "Generating Rosenpass client1 keypair"
  rosenpass gen-keys \
    --secret-key "$ETC_RP/client1.rosenpass-secret" \
    --public-key "$ETC_RP/client1.rosenpass-public"
fi

# ---------- WireGuard config ---------------------------------------------
log "Writing $ETC_WG/$WG_IFACE.conf"
cat >"$ETC_WG/$WG_IFACE.conf" <<EOF
# Cloak VPN — WireGuard server config
# Generated by setup.sh. Rosenpass rotates PresharedKey every ~120s.
[Interface]
Address = $SERVER_V4/24, $SERVER_V6/64
ListenPort = $WG_PORT
PrivateKey = $WG_SERVER_PRIV
PostUp   = iptables  -t nat -A POSTROUTING -s $WG_NET_V4 -o $ETH_IFACE -j MASQUERADE
PostUp   = ip6tables -t nat -A POSTROUTING -s $WG_NET_V6 -o $ETH_IFACE -j MASQUERADE
PostDown = iptables  -t nat -D POSTROUTING -s $WG_NET_V4 -o $ETH_IFACE -j MASQUERADE
PostDown = ip6tables -t nat -D POSTROUTING -s $WG_NET_V6 -o $ETH_IFACE -j MASQUERADE

[Peer]
# client1 (test client)
PublicKey = $WG_CLIENT_PUB
AllowedIPs = $CLIENT_V4/32, $CLIENT_V6/128
# PresharedKey managed by rosenpass (wg set --preshared-key /dev/stdin)
EOF
chmod 600 "$ETC_WG/$WG_IFACE.conf"

# ---------- Rosenpass config ---------------------------------------------
log "Writing $ETC_RP/server.toml"
cat >"$ETC_RP/server.toml" <<EOF
# Cloak VPN — Rosenpass server config
public_key = "$ETC_RP/server.rosenpass-public"
secret_key = "$ETC_RP/server.rosenpass-secret"
listen = ["0.0.0.0:$RP_PORT", "[::]:$RP_PORT"]
verbosity = "Quiet"

[[peers]]
public_key = "$ETC_RP/client1.rosenpass-public"
# Tell rosenpass to rotate this WireGuard peer's PSK.
key_out = "/run/rosenpass/psk-client1"
EOF

# systemd tmpfiles directory for PSK output
install -d -m 700 /run/rosenpass
cat >/etc/tmpfiles.d/rosenpass.conf <<EOF
d /run/rosenpass 0700 root root - -
EOF

# ---------- systemd services ---------------------------------------------
log "Installing systemd units"
cat >/etc/systemd/system/cloak-rosenpass.service <<EOF
[Unit]
Description=Cloak VPN — Rosenpass post-quantum key-exchange daemon
After=network-online.target wg-quick@$WG_IFACE.service
Requires=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/rosenpass exchange-config $ETC_RP/server.toml
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

# If rosenpass is installed via apt, binary is at /usr/bin
if [[ -x /usr/bin/rosenpass ]]; then
  sed -i 's|/usr/local/bin/rosenpass|/usr/bin/rosenpass|' /etc/systemd/system/cloak-rosenpass.service
fi

# ---------- UFW firewall --------------------------------------------------
log "Configuring UFW firewall (deny-by-default)"
ufw --force reset >/dev/null
ufw default deny incoming
ufw default allow outgoing
ufw allow OpenSSH
ufw allow $WG_PORT/udp  comment 'WireGuard'
ufw allow $RP_PORT/udp  comment 'Rosenpass PQ handshake'
ufw --force enable

# ---------- RAM-only /var/log --------------------------------------------
log "Switching /var/log to tmpfs (RAM-only, wiped on reboot)"
if ! grep -q '/var/log' /etc/fstab.cloak 2>/dev/null; then
  cp /etc/fstab /etc/fstab.cloak.bak 2>/dev/null || true
  if ! grep -qE '^[^#].*[[:space:]]/var/log[[:space:]]' /etc/fstab; then
    echo 'tmpfs /var/log tmpfs defaults,noatime,nodev,nosuid,size=256M 0 0' >>/etc/fstab
  fi
  touch /etc/fstab.cloak
  warn "Reboot required for /var/log tmpfs to take effect."
fi

# ---------- Start services ------------------------------------------------
log "Enabling and starting services"
systemctl daemon-reload
systemctl enable --now wg-quick@$WG_IFACE.service
systemctl enable --now cloak-rosenpass.service

sleep 2
systemctl --no-pager --full status wg-quick@$WG_IFACE.service | head -n 12 || true
systemctl --no-pager --full status cloak-rosenpass.service  | head -n 12 || true

# ---------- Emit client config -------------------------------------------
RP_SERVER_PUB_FILE="$ETC_RP/server.rosenpass-public"
RP_SERVER_PUB_B64=$(base64 -w0 "$RP_SERVER_PUB_FILE")

cat <<EOF

=============================================================================
  Cloak VPN server is up.
=============================================================================

  Endpoint (WireGuard):  $PUBLIC_IP:$WG_PORT
  Endpoint (Rosenpass):  $PUBLIC_IP:$RP_PORT
  Server WG pubkey:      $WG_SERVER_PUB
  Server RP pubkey:      $ETC_RP/server.rosenpass-public  (base64 below)

----- CLIENT CONFIG (test client1) ------------------------------------------

[wireguard]
private_key = $WG_CLIENT_PRIV
address_v4  = $CLIENT_V4/32
address_v6  = $CLIENT_V6/128
dns         = 9.9.9.9, 2620:fe::fe

[wireguard.peer]
public_key = $WG_SERVER_PUB
endpoint   = $PUBLIC_IP:$WG_PORT
allowed_ips = 0.0.0.0/0, ::/0
persistent_keepalive = 25

[rosenpass]
server_public_key_b64 = $RP_SERVER_PUB_B64
server_endpoint       = $PUBLIC_IP:$RP_PORT
psk_rotation_seconds  = 120

-----------------------------------------------------------------------------

  Next:
    1. Reboot once to activate RAM-only /var/log.
    2. On your phone, import the block above via the Cloak VPN app.
    3. Verify PSK rotation:  sudo wg show $WG_IFACE   (latest handshake should refresh every ~2min)

EOF
